// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSyiruQ7PFeanrco4-BPJNYt2ZlIVJNu0',
    appId: '1:651892362107:web:e6f44d288bd3f5ddc5cbde',
    messagingSenderId: '651892362107',
    projectId: 'synram-fa08b',
    authDomain: 'synram-fa08b.firebaseapp.com',
    storageBucket: 'synram-fa08b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi6oalbsESXMhqmSfZ3SgP9Qg_e6vfVaY',
    appId: '1:651892362107:android:0d57bbc2b6cb215ac5cbde',
    messagingSenderId: '651892362107',
    projectId: 'synram-fa08b',
    storageBucket: 'synram-fa08b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4DsFazAtAIVQSG3BagrfQnObEm4JrDmc',
    appId: '1:651892362107:ios:f90d7c40bd2f7ac7c5cbde',
    messagingSenderId: '651892362107',
    projectId: 'synram-fa08b',
    storageBucket: 'synram-fa08b.firebasestorage.app',
    iosBundleId: 'com.example.newproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4DsFazAtAIVQSG3BagrfQnObEm4JrDmc',
    appId: '1:651892362107:ios:f90d7c40bd2f7ac7c5cbde',
    messagingSenderId: '651892362107',
    projectId: 'synram-fa08b',
    storageBucket: 'synram-fa08b.firebasestorage.app',
    iosBundleId: 'com.example.newproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSyiruQ7PFeanrco4-BPJNYt2ZlIVJNu0',
    appId: '1:651892362107:web:658365f4cb3a52e2c5cbde',
    messagingSenderId: '651892362107',
    projectId: 'synram-fa08b',
    authDomain: 'synram-fa08b.firebaseapp.com',
    storageBucket: 'synram-fa08b.firebasestorage.app',
  );
}
